{% set version = "1.2.4" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 649ecab692fade3cbfcf967ff936496b0cfba0af00a55dfaacd82bdda5cb2279

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" --global-option="-j${CPU_COUNT}" --no-use-pep517  # [unix]
  entry_points:
    - matplotlib = pandas:plotting._matplotlib
  skip: true  # [py<37]

requirements:
  build:
    # - python                                 # [build_platform != target_platform]
    # - cython                                 # [build_platform != target_platform]
    # - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.16
    - numpy >=1.17.3
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.7.3
    - pytz >=2017.2

test:
  requires:
    - hypothesis >=3.58
    - pytest >=5.0.1
    - pytest-xdist 
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
