{% set tests_to_skip = "_not_a_real_test" %}
{% set version = "2.2.3" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 4f18ba62b61d7e192368b84517265a99b4d7ee8912f8708660fb4a366cc82667

build:
  number: 1
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    # Cross-compilation stuff vendored from numpy-feedstock
    # necessary for cross-compilation to point to the right env
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig                                    # [build_platform != target_platform]
    - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
    - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.5                         # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.0.5
    - numpy
    - versioneer
    - meson =1.2.1
    - meson-python =0.13.1
    - tomli  # [py<311]
    - ninja
  run:
    - python
    # Add only the lowest-supported numpy version from pyproject.toml here,
    # no need to worry about old versions that don't support a given Python version.
    - numpy >=1.22.4
    - python-dateutil >=2.8.1
    - pytz >=2020.1, <2024.2
    - python-tzdata >=2022a
  run_constrained:
    - beautifulsoup4 >=4.11.2
    - blosc >=1.21.3
    - bottleneck >=1.3.6
    - fastparquet >=2022.12.0
    - fsspec >=2022.11.0
    - gcsfs >=2022.11.0
    - lxml >=4.9.2
    - matplotlib >=3.6.3
    - numba >=0.56.4
    - numexpr >=2.8.4
    - pyqt5 >=5.15.8
    - qtpy >=2.3.0
    - openpyxl >=3.1.0
    - psycopg2 >=2.9.6
    - pyreadstat >=1.2.0
    - pytables >=3.8.0
    - pyxlsb >=1.0.10
    - s3fs >=2022.11.0
    - scipy >=1.10.0
    - sqlalchemy >=2.0.0
    - tabulate >=0.9.0
    - tzdata >=2022.7
    - xarray >=2022.12.0
    - xlsxwriter >=3.0.5
    - zstandard >=0.19.0

test:
  imports:
    - pandas
  commands:
    - pip check
    # Skip test suite on PyPy as it segfaults there
    # xref: https://github.com/conda-forge/pandas-feedstock/issues/148
    #
    # do not run test suite in emulation because it takes ~5h; rely on upstream CI for aarch
    {% set markers = ["not clipboard", "not single_cpu", "not slow", "not network", "not db"] %}
    {% set extra_args = ["-m " + " and ".join(markers)] %}
    {% set tests_to_skip = "_not_a_real_test" %}
    {% set extra_args = extra_args + ["-k", "not (" + tests_to_skip + ")", "--no-strict-data-files"] %}
    - python -c "import pandas; pandas.test(extra_args={{ extra_args }})"  # [(build_platform == target_platform) and (python_impl == "cpython")]
  requires:
    - pip
    - pytest >=6.0
    - pytest-xdist >=1.31
    - pytest-cov
    - boto3
    - hypothesis
    - numpy
    - psutil
    - tomli  # [py<311]

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: >-
    Powerful data structures for data analysis, time series, and statistics
  doc_url: https://pandas.pydata.org/docs/
  dev_url: https://github.com/pandas-dev/pandas

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
    - mroeschke
    - datapythonista
    - phofl
    - lithomas1
    - marcogorelli
