{% set name = "pandas" %}
{% set version="0.20.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: a777e07633d83d546c55706420179551c8e01075b53c497dcf8ae4036766bc66

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
  run:
    - python
    - numpy >=1.7  # [py27]
    - numpy >=1.9  # [py35]
    - numpy >=1.11  # [py36]
    - python-dateutil
    - pytz
    - bottleneck
    - numexpr

test:
  imports:
    - pandas
  commands:
    - conda inspect linkages -p $PREFIX pandas  # [not win]
    - conda inspect objects -p $PREFIX pandas  # [osx]

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
