{% set version = "1.5.1" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 249cec5f2a5b22096440bd85c33106b6102e0672204abd2d5c014106459804ee

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" --global-option="-j1" --no-use-pep517  # [unix]
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=51.0.0
    - cython >=0.29.24,<3
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.8.1
    - pytz >=2020.1

test:
  imports:
    - pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
    - mroeschke
    - datapythonista
    - phofl
    - lithomas1
    - marcogorelli
