{% set version = "1.2.3" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: df6f10b85aef7a5bb25259ad651ad1cc1d6bb09000595cab47e718cbac250b1d

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" --global-option="-j${CPU_COUNT}" --no-use-pep517  # [unix]
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.16
    - numpy 1.15.4  # [(py != 38) and not (aarch64 or ppc64le)]
    - numpy 1.16  # [(py == 38) and not (aarch64 or ppc64le)]
    - numpy  # [aarch64 or ppc64le]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.7.3
    - pytz >=2017.2

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
