{% set tests_to_skip = "_not_a_real_test" %}
{% set version = "3.0.0" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: e05e1af93b977f7eafa636d043f9f94c7ee3ac81af99c13508215942e64c993b

build:
  number: 3
  skip: true  # [py < 311]
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    # Cross-compilation stuff vendored from numpy-feedstock
    # necessary for cross-compilation to point to the right env
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig                                    # [build_platform != target_platform]
    - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
    - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.5                         # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.0.5
    - numpy
    - versioneer
    - meson >=1.4.0
    - meson-python >=0.15.0
    - tomli  # [py<311]
    - ninja
  run:
    - python
    # Add only the lowest-supported numpy version from pyproject.toml here,
    # no need to worry about old versions that don't support a given Python version.
    - numpy >=1.26.0
    - python-dateutil >=2.8.2
    - python-tzdata >=2023.3
  run_constrained:
    - adbc-driver-postgresql >=1.2.0
    - adbc-driver-sqlite >=1.2.0
    - beautifulsoup4 >=4.12.3
    - blosc >=1.21.3
    - bottleneck >=1.4.2
    - fastparquet >=2024.11.0
    - fsspec >=2024.10.0
    - gcsfs >=2024.10.0
    - html5lib >=1.1
    - hypothesis >=6.116.0
    - jinja2 >=3.1.5
    - lxml >=5.3.0
    - matplotlib >=3.9.3
    - numba >=0.60.0
    - numexpr >=2.10.2
    - odfpy >=1.4.1
    - openpyxl >=3.1.5
    - psycopg2 >=2.9.10
    - pyarrow >=13.0.0
    - pyiceberg >=0.8.1
    - pymysql >=1.1.1
    - pyqt5 >=5.15.9
    - pyreadstat >=1.2.8
    - pytables >=3.10.1
    - pytest >=8.3.4
    - pytest-xdist >=3.6.1
    - python-calamine >=0.3.0
    - pytz >=2024.2
    - pyxlsb >=1.0.10
    - qtpy >=2.4.2
    - scipy >=1.14.1
    - s3fs >=2024.10.0
    - sqlalchemy >=2.0.36
    - tabulate >=0.9.0
    - xarray >=2024.10.0
    - xlrd >=2.0.1
    - xlsxwriter >=3.2.0
    - zstandard >=0.23.0

test:
  imports:
    - pandas
  commands:
    - pip check
    # Skip test suite on PyPy as it segfaults there
    # xref: https://github.com/conda-forge/pandas-feedstock/issues/148
    #
    # do not run test suite in emulation because it takes ~5h; rely on upstream CI for aarch
    {% set markers = ["not clipboard", "not single_cpu", "not slow", "not network", "not db"] %}
    {% set extra_args = ["-m " + " and ".join(markers)] %}
    {% set tests_to_skip = "_not_a_real_test" %}
    {% set extra_args = extra_args + ["-k", "not (" + tests_to_skip + ")", "--no-strict-data-files"] %}
    - python -c "import pandas; pandas.test(extra_args={{ extra_args }})"  # [(build_platform == target_platform) and (python_impl == "cpython")]
  requires:
    - pip
    - pytest >=8.3.4
    - pytest-xdist >=3.6.1
    - pytest-cov
    - boto3
    - hypothesis
    - numpy
    - tomli  # [py<311]

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: >-
    Powerful data structures for data analysis, time series, and statistics
  doc_url: https://pandas.pydata.org/docs/
  dev_url: https://github.com/pandas-dev/pandas

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
    - mroeschke
    - datapythonista
    - phofl
    - lithomas1
    - marcogorelli
