{% set version="0.19.2" %}

package:
  name: pandas
  version: {{ version }}

source:
  fn: pandas-{{ version }}.tar.gz
  url: https://github.com/pydata/pandas/archive/v{{ version }}.tar.gz
  sha256: af634dd6ed3ca1f8635183f41e7f7769108531ccca8213067d9627857461702e

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy  x.x
  run:
    - python
    - numpy  x.x
    - python-dateutil
    - pytz

test:
  imports:
    - pandas
  commands:
    - conda inspect linkages -p $PREFIX pandas  # [not win]
    - conda inspect objects -p $PREFIX pandas  # [osx]

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
