{% set version = "0.25.0" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas/pandas-{{ version }}.tar.gz
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 914341ad2d5b1ea522798efa4016430b66107d05781dbfe7cf05eba8f37df995

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28.2
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.6.1
    - pytz >=2017.2

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
