{% set version = "0.23.0" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas/pandas-{{ version }}.tar.gz
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 84ab1d50590cb2d9554211f164dc1b1a216bc94da2ba922aed2690c83f248fd9

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil
    - pytz

test:
  imports:
    - pandas
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
