{% set version = "1.1.0rc0" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 87bec0cca6e2435dc96bf063cfa332cd11825b48d6199974916acaff5d80ea80
  patches:
    - patches/0001-PKG-No-error-for-osx.patch

build:
  number: 1
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.16
    - numpy 1.15.4  # [py != 38]
    - numpy 1.16  # [py == 38]
    - numpy  # [aarch64 or ppc64le]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.7.3
    - pytz >=2017.2

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
