{% set version = "1.2.0rc0" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: c81d202f2077dfe09f722ec566ceade4276e92f66b7156214a5b9f7c75fa1be9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.16
    - numpy 1.15.4  # [(py != 38) and not (aarch64 or ppc64le)]
    - numpy 1.16  # [(py == 38) and not (aarch64 or ppc64le)]
    - numpy  # [aarch64 or ppc64le]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.7.3
    - pytz >=2017.2

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
