{% set version = "2.0.0" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: cda9789e61b44463c1c4fe17ef755de77bcd13b09ba31c940d20f193d63a5dc8

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" --global-option="-j1" --no-use-pep517  # [unix]
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=51.0.0
    - cython >=0.29.24,<3
    - numpy
    - versioneer
    - tomli  # [py<311]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.8.1
    - pytz >=2020.1
    - tzdata >=2022a

test:
  imports:
    - pandas
  commands:
    - pip check
    # Skip test suite on PyPy as it segfaults there
    # xref: https://github.com/conda-forge/pandas-feedstock/issues/148
    #
    # Also skip `test_rolling_var_numerical_issues` on `ppc64le` as it is a known test failure.
    # xref: https://github.com/conda-forge/pandas-feedstock/issues/149
    {% set markers = ["not clipboard", "not single_cpu"] %}
    {% set markers = markers + ["not arm_slow"] %}   # [aarch64 or ppc64le]
    {% set extra_args = ["-m " + " and ".join(markers)] %}
    {% set extra_args = extra_args + ["--skip-slow", "--skip-network", "--skip-db", "-n=2"] %}
    {% set extra_args = extra_args + ["-k not test_rolling_var_numerical_issues"] %}   # [ppc64le]
    - python -c "import pandas; pandas.test(extra_args={{ extra_args }})"  # [python_impl == "cpython"]
  requires:
    - pip
    - pytest >=6.0
    - pytest-asyncio >=0.17
    - pytest-xdist >=1.31
    - pytest-cov
    - boto3
    - hypothesis
    # Workaround recent NumPy 1.24 deprecations, which cause test failures.
    # xref: https://github.com/conda-forge/pandas-feedstock/issues/150
    - numpy <1.24
    - psutil
    - tomli  # [py<311]

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: >-
    Powerful data structures for data analysis, time series, and statistics
  doc_url: https://pandas.pydata.org/docs/
  dev_url: https://github.com/pandas-dev/pandas

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
    - mroeschke
    - datapythonista
    - phofl
    - lithomas1
    - marcogorelli
