{% set version = "1.3.2" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: cbcb84d63867af3411fa063af3de64902665bb5b3d40b25b2059e40603594e87

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" --global-option="-j${CPU_COUNT}" --no-use-pep517  # [unix]
  entry_points:
    - matplotlib = pandas:plotting._matplotlib
  skip: true  # [py<37]

requirements:
  build:
    # - python                                 # [build_platform != target_platform]
    # - cython                                 # [build_platform != target_platform]
    # - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.21
    - numpy
    - setuptools >=38.6.0
    - wheel
  run:
    - python >=3.7.1
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.7.3
    - pytz >=2017.3
    # Recommended dependencies to achieve large speedups
    # see https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#recommended-dependencies
    - numexpr >=2.7.0
    - bottleneck >=1.2.1

test:
  requires:
    - hypothesis >=3.58
    - pytest >=6.0
    - pytest-xdist 
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.
  dev_url: https://github.com/pandas-dev/pandas
  doc_url: https://pandas.pydata.org/pandas-docs/stable/

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
