schema_version: 1

context:
  version: 3.0.0

package:
  name: pandas
  version: ${{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v${{ version }}/pandas-${{ version }}.tar.gz
  sha256: 0facf7e87d38f721f0af46fe70d97373a37701b1c09f7ed7aeeb292ade5c050f

build:
  number: 1
  skip: match(python, "<3.11")
  script:
    - if: ppc64le
      then: export PYTHONUNBUFFERED=1
    # Cross-compilation stuff vendored from numpy-feedstock
    # necessary for cross-compilation to point to the right env
    - if: build_platform != target_platform
      then: 
        - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
        - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt
    - if: unix
      then:
       - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"
       - ${{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}
      else: ${{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .

requirements:
  build:
    - if: build_platform != target_platform
      then: 
        - python
        - cross-python_${{ target_platform }}
        - cython >=3.0.5
        # TODO: Unpin https://github.com/conda-forge/pandas-feedstock/pull/242#issuecomment-3762956756
        - numpy =2.3
        - meson-python
        - ninja
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.0.5
    # TODO: Unpin https://github.com/conda-forge/pandas-feedstock/pull/242#issuecomment-3762956756
    - numpy =2.3
    - versioneer
    - meson >1.4.1
    - meson-python >=0.17.1
    - ninja
  run:
    - python
    # Add only the lowest-supported numpy version from pyproject.toml here,
    # no need to worry about old versions that don't support a given Python version.
    - numpy >=1.26.0
    - python-dateutil >=2.8.2
    - if: win
      then: python-tzdata
  run_constraints:
    - adbc-driver-postgresql >=1.2.0
    - adbc-driver-sqlite >=1.2.0
    - beautifulsoup4 >=4.12.3
    - blosc >=1.21.3
    - bottleneck >=1.4.2
    - fastparquet >=2024.11.0
    - fsspec >=2024.10.0
    - gcsfs >=2024.10.0
    - html5lib >=1.1
    - hypothesis >=6.116.0
    - jinja2 >=3.1.5
    - lxml >=5.3.0
    - matplotlib >=3.9.3
    - numba >=0.60.0
    - numexpr >=2.10.2
    - odfpy >=1.4.1
    - openpyxl >=3.1.5
    - psycopg2 >=2.9.10
    - pyarrow >=13.0.0
    - pyiceberg >=0.8.1
    - pymysql >=1.1.1
    - pyqt5 >=5.15.9
    - pyreadstat >=1.2.8
    - pytables >=3.10.1
    - pytest >=8.3.4
    - pytest-xdist >=3.6.1
    - python-calamine >=0.3.0
    - pytz >=2024.2
    - pyxlsb >=1.0.10
    - qtpy >=2.4.2
    - scipy >=1.14.1
    - s3fs >=2024.10.0
    - sqlalchemy >=2.0.36
    - tabulate >=0.9.0
    - xarray >=2024.10.0
    - xlrd >=2.0.1
    - xlsxwriter >=3.2.0
    - zstandard >=0.23.0

tests:
  - python:
      imports:
        - pandas
      pip_check: true
  # do not run test suite in emulation because it takes ~5h; rely on upstream CI for aarch
  - if: build_platform == target_platform
    then:
      - requirements:
          run:
            - pytest >=8.3.4
            - hypothesis

        script:
          interpreter: python
          content: |
            import pandas
            markers = ["not clipboard", "not single_cpu", "not slow", "not network", "not db"]
            extra_args = ["-m " + " and ".join(markers)]
            extra_args = extra_args + ["--no-strict-data-files"]
            pandas.test(extra_args=extra_args)

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: >-
    Powerful data structures for data analysis, time series, and statistics
  homepage: http://pandas.pydata.org
  repository: https://github.com/pandas-dev/pandas
  documentation: https://pandas.pydata.org/docs/

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
    - mroeschke
    - datapythonista
    - phofl
    - lithomas1
    - marcogorelli
