schema_version: 1

context:
  version: "3.1.0rc0"

package:
  name: pandas
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pandas/pandas-${{ version }}.tar.gz
  sha256: f974ad866f5fadbaf7741bd8f5b6e07815dfa04839853deb262da2663819b40b

build:
  number: 0
  script:
    - if: ppc64le
      then: export PYTHONUNBUFFERED=1
    # Cross-compilation stuff vendored from numpy-feedstock
    # necessary for cross-compilation to point to the right env
    - if: build_platform != target_platform
      then:
        - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
        - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt
    - if: unix
      then:
        - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"
        - ${{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}
      else: ${{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=3.0.5
        - numpy
        - meson-python
        - ninja
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.0.5
    - numpy
    - versioneer
    - meson >1.4.1
    - meson-python >=0.17.1
    - ninja
  run:
    - python
    # Add only the lowest-supported numpy version from pyproject.toml here,
    # no need to worry about old versions that don't support a given Python version.
    - numpy >=2.0.2
    - python-dateutil >=2.9.0
    - if: win
      then: python-tzdata
  run_constraints:
    - adbc-driver-postgresql >=1.7.0
    - adbc-driver-sqlite >=1.7.0
    - beautifulsoup4 >=4.13.4
    - blosc >=1.21.3
    - bottleneck >=1.5.0
    - fastparquet >=2024.11.0
    - fsspec >=2025.7.0
    - gcsfs >=2025.7.0
    - html5lib >=1.1
    - hypothesis >=6.116.0
    - jinja2 >=3.1.5
    - lxml >=6.0.0
    - matplotlib >=3.10.5
    - numba >=0.61.2
    - numexpr >=2.11.0
    - odfpy >=1.4.1
    - openpyxl >=3.1.5
    - psycopg2 >=2.9.10
    - pyarrow >=16.0.0
    - pyiceberg >=0.9.1
    - pymysql >=1.1.1
    - pyqt5 >=5.15.11
    - pyreadstat >=1.3.0
    - pytables >=3.10.2
    - python-calamine >=0.4.0
    - pytz >=2024.2
    - pyxlsb >=1.0.10
    - qtpy >=2.4.3
    - scipy >=1.16.1
    - s3fs >=2025.7.0
    - sqlalchemy >=2.0.42
    - tabulate >=0.9.0
    - xarray >=2025.7.1
    - xlrd >=2.0.2
    - xlsxwriter >=3.2.5
    - zstandard >=0.23.0

tests:
  - python:
      imports:
        - pandas
      pip_check: true
  # Skip test suite on PyPy as it segfaults there
  # xref: https://github.com/conda-forge/pandas-feedstock/issues/148
  #
  # do not run test suite in emulation because it takes ~5h; rely on upstream CI for aarch
  - if: (build_platform == target_platform) and (python_impl == "cpython")
    then:
      - requirements:
          run:
            - pip
            - pytest >=8.3.4
            - pytest-xdist >=3.6.1
            - pytest-cov
            - boto3
            - hypothesis
            - numpy

        script:
          interpreter: python
          content: |
            import pandas
            markers = ["not clipboard", "not single_cpu", "not slow", "not network", "not db"]
            extra_args = ["-m " + " and ".join(markers)]
            tests_to_skip = "_not_a_real_test"
            extra_args = extra_args + ["-k", "not (" + tests_to_skip + ")", "--no-strict-data-files"]
            pandas.test(extra_args=extra_args)

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: >-
    Powerful data structures for data analysis, time series, and statistics
  homepage: http://pandas.pydata.org
  repository: https://github.com/pandas-dev/pandas
  documentation: https://pandas.pydata.org/docs/

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
    - mroeschke
    - datapythonista
    - phofl
    - lithomas1
    - marcogorelli
